# Generated by Django 4.2.18 on 2025-03-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0003_customuser_birthdate_customuser_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='membership',
            field=models.CharField(choices=[('community', 'Community Member'), ('key_access', 'Key Access Member'), ('workspace', 'Creative Workspace Member')], default='community', max_length=20),
        ),
    ]
