# Generated by Django 4.2.18 on 2025-03-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0004_alter_customuser_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interest',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Design', 'Design'), ('Business', 'Business'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Art', 'Art'), ('Science', 'Science'), ('Law', 'Law'), ('Politics', 'Politics'), ('Environment', 'Environment'), ('Social Media', 'Social Media'), ('Travel', 'Travel'), ('Lifestyle', 'Lifestyle'), ('Real Estate', 'Real Estate'), ('Retail', 'Retail'), ('Music', 'Music')], default='Technology', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
