# Generated by Django 4.2.20 on 2025-03-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0005_alter_customuser_email_alter_customuser_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approvedmember',
            field=models.BooleanField(default=False),
        ),
    ]
