# Generated by Django 4.2.18 on 2025-03-10 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0006_customuser_approvedmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 15, 22, 24, 845427, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='membership',
            field=models.CharField(choices=[('Community', 'Community Member'), ('Key Access', 'Key Access Member'), ('Workspace', 'Creative Workspace Member')], default='community', max_length=20),
        ),
    ]
