# Generated by Django 4.2.20 on 2025-03-24 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0007_customuser_created_at_alter_customuser_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 4, 42, 28, 44569, tzinfo=datetime.timezone.utc)),
        ),
    ]
