# Generated by Django 5.1.7 on 2025-03-18 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AuthenticationApp", "0007_customuser_created_at_alter_customuser_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 18, 2, 11, 5, 450252, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="interest",
            field=models.CharField(
                choices=[
                    ("Technology", "Technology"),
                    ("Design", "Design"),
                    ("Business", "Business"),
                    ("Marketing", "Marketing"),
                    ("Finance", "Finance"),
                    ("Education", "Education"),
                    ("Healthcare", "Healthcare"),
                    ("Entertainment", "Entertainment"),
                    ("Sports", "Sports"),
                    ("Art", "Art"),
                    ("Science", "Science"),
                    ("Law", "Law"),
                    ("Environment", "Environment"),
                    ("Social Media", "Social Media"),
                    ("Other", "Other"),
                ],
                default="Technology",
                max_length=255,
            ),
        ),
    ]
