# Generated by Django 4.2.20 on 2025-03-24 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0008_alter_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 12, 20, 22, 986589, tzinfo=datetime.timezone.utc)),
        ),
    ]
