# Generated by Django 5.1.7 on 2025-03-18 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AuthenticationApp", "0008_alter_customuser_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 18, 2, 19, 39, 594990, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
