# Generated by Django 4.2.20 on 2025-03-26 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0009_alter_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 26, 5, 56, 53, 830379, tzinfo=datetime.timezone.utc)),
        ),
    ]
