# Generated by Django 5.1.7 on 2025-03-19 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AuthenticationApp", "0009_alter_customuser_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 19, 9, 14, 21, 306795, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="interest",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
