# Generated by Django 5.1.7 on 2025-03-20 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AuthenticationApp", "0010_alter_customuser_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 20, 2, 6, 42, 698689, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
