# Generated by Django 4.2.20 on 2025-03-26 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0010_alter_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 26, 6, 19, 21, 370422, tzinfo=datetime.timezone.utc)),
        ),
    ]
