# Generated by Django 4.2.20 on 2025-03-26 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0011_alter_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 26, 9, 39, 57, 1212, tzinfo=datetime.timezone.utc)),
        ),
    ]
