# Generated by Django 5.1.7 on 2025-03-20 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AuthenticationApp", "0012_customuser_security_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 20, 2, 41, 5, 431660, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
