# Generated by Django 4.2.20 on 2025-03-29 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0012_alter_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 12, 4, 5, 988507, tzinfo=datetime.timezone.utc)),
        ),
    ]
