# Generated by Django 4.2.20 on 2025-03-29 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0013_alter_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 15, 25, 27, 994386, tzinfo=datetime.timezone.utc)),
        ),
    ]
