# Generated by Django 5.1.7 on 2025-03-30 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AuthenticationApp", "0014_alter_customuser_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="security_answer",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="security_question",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 30, 13, 24, 39, 247559, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="interest",
            field=models.CharField(
                choices=[
                    ("Technology", "Technology"),
                    ("Design", "Design"),
                    ("Business", "Business"),
                    ("Marketing", "Marketing"),
                    ("Finance", "Finance"),
                    ("Education", "Education"),
                    ("Healthcare", "Healthcare"),
                    ("Entertainment", "Entertainment"),
                    ("Sports", "Sports"),
                    ("Art", "Art"),
                    ("Science", "Science"),
                    ("Law", "Law"),
                    ("Politics", "Politics"),
                    ("Environment", "Environment"),
                    ("Social Media", "Social Media"),
                    ("Travel", "Travel"),
                    ("Lifestyle", "Lifestyle"),
                    ("Real Estate", "Real Estate"),
                    ("Retail", "Retail"),
                    ("Music", "Music"),
                ],
                default="Technology",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="membership",
            field=models.CharField(
                choices=[
                    ("Community", "Community Member"),
                    ("Key Access", "Key Access Member"),
                    ("Workspace", "Creative Workspace Member"),
                ],
                default="Community",
                max_length=20,
            ),
        ),
    ]
