# Generated by Django 4.2.18 on 2025-03-29 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0014_alter_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 19, 49, 47, 757715, tzinfo=datetime.timezone.utc)),
        ),
    ]
