# Generated by Django 5.1.7 on 2025-03-30 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AuthenticationApp", "0015_remove_customuser_security_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 30, 13, 30, 3, 513141, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="interest",
            field=models.CharField(default="Technology", max_length=255),
        ),
    ]
