# Generated by Django 4.2.18 on 2025-03-30 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0015_alter_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 30, 7, 4, 1, 239168, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='membership',
            field=models.CharField(choices=[('Community', 'Community Member'), ('Key Access', 'Key Access Member'), ('Workspace', 'Creative Workspace Member')], default='Community', max_length=20),
        ),
    ]
