# Generated by Django 4.2.18 on 2025-03-30 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0018_alter_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 30, 7, 6, 31, 554416, tzinfo=datetime.timezone.utc)),
        ),
    ]
