# Generated by Django 5.1.7 on 2025-03-31 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AuthenticationApp", "0020_alter_customuser_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="security_answer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="security_question",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 31, 23, 29, 25, 665017, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="interest",
            field=models.CharField(default="Technology", max_length=255),
        ),
    ]
