# Generated by Django 5.1.7 on 2025-03-31 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AuthenticationApp", "0021_customuser_security_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 31, 23, 48, 30, 579071, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
