# Generated by Django 5.1.7 on 2025-03-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DashboardApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
    ]
