# Generated by Django 4.2.20 on 2025-03-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0002_event_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('resources', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
