# Generated by Django 4.2.20 on 2025-03-29 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DashboardApp', '0004_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='enrolled_lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
